spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dummy?serverTimezone=Asia/Seoul
    username: dummy
    password: dummy
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
