name: Java CD with SSH

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Transfer script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "scripts/deploy.sh"
          target: "/home/ec2-user/deploy"
      - name: Transfer jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ec2-user/deploy"
      - name: Execute script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: chmod +x /home/ec2-user/deploy/deploy.sh && /home/ec2-user/deploy/deploy.sh
